name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello,this is GEORGE LANG'AT,An AI enthusiast,and python developer"
        pr-message: "Welcome into my platform,we Innovate, Connect and Empower together.' first pull request"
